spring:
  cloud:
    function:
      definition: reservationProducer;reservationConsumer
    stream:
      default-binder: kafka
      kafka:
        bindings:
          reservationProducer-out-0:
            producer:
              configuration:
                value.serializer: com.ishan.phadte.dto.coverters.ReservationSerializer
          reservationConsumer-in-0:
            consumer:
              batch-mode: true
              configuration:
                value.deserializer: com.ishan.phadte.dto.coverters.ReservationDeSerializer
        binder:
          brokers: localhost:9092
            
      bindings:
        reservationProducer-out-0:
            binder: kafka
            destination : reservations-topic
            producer:
                useNativeEncoding: true # This enables using the custom serializer
        reservationConsumer-in-0:
            binder: kafka
            destination : reservations-topic
            consumer:
              use-native-decoding: true # This enables using the custom deserializer
  kafka:
    producer:
      properties:
          queue.buffering.max.messages: 5  # Maximum number of messages to buffer
  #     bootstrap-servers: localhost:9092 #Produce to Broker 2
  #     value.serializer: com.ishan.phadte.dto.coverters.MessageSerializer
  #     default-topic: second-topic #Topic on broker 2

  # kafka:
  #   bootstrap-servers: localhost:9092
  #   producer:
  #     key-serializer: org.apache.kafka.common.serialization.StringSerializer
  #     value-serializer: org.apache.kafka.common.serialization.StringSerializer
  #   consumer:
  #     key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  #     value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  #     group-id: my-group
  #     auto-offset-reset: earliest

management:
  endpoints:
    web:
      exposure:
        include: health,beans  # Include multiple endpoints
  endpoint:
    health:
      show-details: always  # Show health details
    info:
      enabled: true  # Ensure the info endpoint is enabled

    beans:
      enabled: true  # Ensure the info endpoint is enabled

# server:
#   port: 8080
#   servlet:
#     context-path: /myapp
#     session:
#       timeout: 30m
#   tomcat:
#     max-threads: 200
#     connection-timeout: 20000
#     access-log:
#       enabled: true
#       pattern: common
