spring:
  cloud:
    function:
      definition: consumer;producer
    stream:
      kafka:
        bindings:
          producer-out-0:
            producer:
              configuration:
                client.id: producer0
                value.serializer: com.ishan.phadte.dto.coverters.ReservationSerializer
                
          consumer-in-0:
            consumer:
              configuration:
                value.deserializer: com.ishan.phadte.dto.coverters.ReservationDeSerializer

        binder:
          brokers: localhost:9092
            
      bindings:
        producer-out-0:
            destination : first-topic
            producer:
              group: reserve-group
              useNativeEncoding: true # This enables using the custom serializer

        consumer-in-0:
            destination : first-topic
            consumer:
              group: reserve-group
              use-native-decoding: true # This enables using the custom deserializer

management:
  endpoints:
    web:
      exposure:
        include: health,info,beans  # Include the beans endpoint among others
  endpoint:
    beans:
      enabled: true  # Ensure that the beans endpoint is enabled
