spring:
  cloud:
    function:
      definition: consumer;producer
    stream:
      default-binder: kafka
      kafka:
        bindings:
          producer-out-0:
            producer:
              configuration:
                value.serializer: com.ishan.phadte.dto.coverters.MessageSerializer
          consumer-in-0:
            consumer:
              configuration:
                value.deserializer: com.ishan.phadte.dto.coverters.MessageDeSerializer
        binder:
          brokers: localhost:9092
            
      bindings:
        producer-out-0:
            destination : first-topic
            producer:
                useNativeEncoding: true # This enables using the custom serializer
        consumer-in-0:
            destination : first-topic
            consumer:
              use-native-decoding: true # This enables using the custom deserializer